name: Contextos
run-name: ACtividad 4
on: [push]
env:
  VARIABLE_NUEVA: "no me ayudas IA"
jobs:
  check-main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $VARIABLE_NUEVA"